### ISSUE TITLE
Morning Session 01/13

### ISSUE THREAD

**Issue by orozCoding** [HAMMAS-SALEEM/ToDoList#2]
Great work this far with the project 
<img src="https://media4.giphy.com/media/xHMIDAy1qkzNS/giphy.gif"/>

Here are some changes we suggest to do:

- It would be great to change the website title to something related to the project, for example "To Do List".
- Remember the best practices related to IDs and Class names. Some of your IDs in your HTML, such are "toDoName" would look better as "to-do-name".

Keep it going! ❤️

**Comment by HAMMAS-SALEEM** [comment]
Thanks for the feedback. I have implemented all changes you suggested.
Keep doing this again and again.
I will appreciate that. 👍
